using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TextSyncModel
{
    [RealtimeProperty(1, true, true)]
    private string _kommentar;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TextSyncModel : RealtimeModel {
    public string kommentar {
        get {
            return _kommentarProperty.value;
        }
        set {
            if (_kommentarProperty.value == value) return;
            _kommentarProperty.value = value;
            InvalidateReliableLength();
            FireKommentarDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TextSyncModel model, T value);
    public event PropertyChangedHandler<string> kommentarDidChange;
    
    public enum PropertyID : uint {
        Kommentar = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _kommentarProperty;
    
    #endregion
    
    public TextSyncModel() : base(null) {
        _kommentarProperty = new ReliableProperty<string>(1, _kommentar);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _kommentarProperty.UnsubscribeCallback();
    }
    
    private void FireKommentarDidChange(string value) {
        try {
            kommentarDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _kommentarProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _kommentarProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Kommentar: {
                    changed = _kommentarProperty.Read(stream, context);
                    if (changed) FireKommentarDidChange(kommentar);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _kommentar = kommentar;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
